name: Checkov IaC Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkov:
    name: Checkov Terraform Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@a8664e3a0549367977f0cda990a34311835c87c0
        with:
          directory: terraform
          framework: terraform